/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>BagBar.com - Use the Bages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <img
          className="h-[700px] w-[100%] md:w-[100%] sm:w-[100%]"
          src="/homelogo.jpg"
          alt="LGOG"
        />
      </div>
      <section className="text-gray-600 body-font -mb-[150px]">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-wrap w-full mb-20 flex-col items-center text-center">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">
              Welcome to ClothBar.com
            </h1>
            <p className="lg:w-1/2 w-full leading-relaxed text-gray-500">
              A new report from Cientifica Research examines the markets for
              textile-based wearable technologies
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
